pipeline {

 

    agent any

               parameters {

        string(defaultValue: "", description: 'What environment?', name: 'Environment')

        // choices are newline separated

        choice(choices: 'US-EAST-1\nUS-WEST-2', description: 'What AWS region?', name: 'region')

    }

    tools {

        maven 'Maven Home'

        jdk 'Java'

    }

    stages {

        stage ('Checkout'){

            steps

                                                {

                                                                git (

                                                                                url: 'https://github.com/DpkOracle/Multibranch.git',

                                                                                credentialsId: '9b7dc132-cd86-428a-afdc-1dff935d5b85'

                                                                )

                                                }

                                               

            }

                               

    }

}
